// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"share_board/app/model/internal"
)

// Page is the golang structure for table page.
type Page internal.Page

// Fill with you ideas below.