// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"share_board/app/dao/internal"
)

// pageDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type pageDao struct {
	*internal.PageDao
}

var (
	// Page is globally public accessible object for table page operations.
	Page = &pageDao{
		internal.Page,
	}
)

// Fill with you ideas below.